### ISSUE TITLE
Qt Wayland apps don't run

### ISSUE THREAD

**Issue by plfiorini** [debarshiray/toolbox#104]
Looks like only `$DISPLAY` is set automatically, not `$WAYLAND_DISPLAY`

**Comment by debarshiray** [comment]
Out of curiosity, which application was it? Specifically, what GUI toolkit was it using?

**Comment by plfiorini** [comment]
QtCreator, Qt toolkit

**Comment by plfiorini** [comment]
Using fedora-toolbox on Fedora 29

**Comment by matthiasclasen** [comment]
The summary is misleading: GTK wayland apps run just fine.

**Comment by halfline** [comment]
`WAYLAND_DISPLAY` (and it's lesser used cousin `WAYLAND_SOCKET`) are both optional environment variables.  By default wayland clients are expected to connect to `$XDG_RUNTIME_DIR/wayland-0` unless explicitly overridden in the environment.  It sounds like Qt may need a fix to be fully compliant.

**Comment by plfiorini** [comment]
Even though it seems to be a problem restricted to Qt, why don't you forward `WAYLAND_DISPLAY` and `WAYLAND_SOCKET`?

**Comment by matthiasclasen** [comment]
Environment variables often cause as many problems as they solve. Qt should use the socket in the well-known location without any extra prodding.

**Comment by plfiorini** [comment]
Let's forget about Qt for a moment. That's a separate issue.
If the user had changed those variables and toolbox will never forward them, it will be impossible to use them, unless the user set them again but that's looks like a bad user experience.

**Comment by grulja** [comment]
I did little digging, it looks that Qt uses **wl_display_connect(nullptr)**, which according to documentation:

> Connect to the Wayland display named name. If name is NULL, its value will be replaced with the WAYLAND_DISPLAY environment variable if it is set, otherwise display 'wayland-0' will be used.

So in my opinion this should work fine, unless XDG_RUNTIME_DIR is not set.

**Comment by debarshiray** [comment]
When it came to environment variables, we tried to locate the smallest subset that's not set by the user's usual shell start-up scripts, and is necessary to get a seamless integration with the host. `WAYLAND_DISPLAY` got left out because the vast majority of Wayland displays that aren't used for debugging or development can be reached at `wayland-0`.

Although, I wish I understood why it hasn't been working for you. Do you really have a Wayland display that's not `wayland-0`?

Anyway, #118 will now forward `WAYLAND_DISPLAY` if it's set on the host, and as far as I can make out, Mutter seems to be setting it on Fedora Workstation. I hope that gets you off the hook.

**Comment by debarshiray** [comment]
Thanks for digging that up, @grulja
