### ISSUE TITLE
Issue with default image release on non-fedora hosts

### ISSUE THREAD

**Issue by andrunko** [debarshiray/toolbox#131]
While working on integrating toolbox on EndlessOS (eos) I noticed that `toolbox create` (without params) tries to create an image from `fedora-toolbox:3.6.0` by default.

This happens because toolbox gets the default release version from `/etc/os-release` (VERSION_ID) . Given that the default image name is hardcoded to `fedora-toolbox`, toolbox should probably only get the default version from `/etc/os-release` if the `ID` is fedora, otherwise it should default to some fedora release (e.g. 29).

There are a few other options to consider also:
- instead of defaulting to `fedora-toolbox` when no image is provided via cmdline, use the `ID` from `/etc/os-release` as the base name: `$ID-toolbox:$VERSION_ID`
  - this way it at least would not try to download a `fedora-toolbox` image from a completely unrelated version
  - that would probably require changes to the default registry also or maybe we should use a list of registries instead (e.g. using the ones configured in `/etc/containers/registries.conf`)
  - If we go with that, note also that for Debian (`ID=debian`) hosts we should probably get the release version from `/etc/debian_version`, given that `VERSION_ID` is set to a number while the base docker debian images use the release name as version (e.g. `debian:buster` instead of `debian:10`) and I would suspect a potential `debian-toolbox` image would follow the same standard on image naming
- or maybe I should just patch the eos toolbox package directly, but that would mean users from non-fedora hosts trying to use toolbox from git would always (unless `VERSION_ID` matches the ones from fedora) have to pass the image/release from cmdline (maybe not a big deal)

I can provide patches as needed, just want to check first what are your thoughts on the options above (any other ideas?) and whether this is something we want to "fix" - I know it is not a priority for toolbox to work on non-fedora hosts by default, but it would be nice to support it oob when running without extra params.

**Comment by debarshiray** [comment]
Thanks for getting in touch @andrunko !

At the moment the Toolbox implementation totally assumes Fedora everywhere. Not because it's intentional, but simply because it started as a prototype for Fedora Silverblue. I'd love to make adjustments, accept patches, etc. to make it more generic. Although, I have a feeling that some of the things would end up being special-cased for specific distributions. eg., the naming of the OCI images like you mentioned.

To start with, changing the name of the default OCI image seems straightforward.

Does Debian have its own Docker registry too? Currently the way the Toolbox looks up registries doesn't involve `/etc/containers/registries.conf` at all. Again not intended, but a consequence of being a prototype around `podman`, and not having access to the backend Go modules that do all this work for `podman` and friends. It needs some digging, but I am sure we can find a way to make things more flexible.

Are there other issues that you ran into?

**Comment by andrunko** [comment]
Thanks @debarshiray - as we discussed on IRC, to start with I will send a patch to make it default to fedora 29 release if ID != fedora on `/etc/os-release` such that `toolbox create` works oob on non-fedora boxes - as otherwise we would need additional changes to the default registry and so on...

Later on we can think about making it default to $ID-toolbox:$VERSION_ID or something.

The other issue I ran into was related to the wheel group not existing on debian based images, but that is another topic for discussion (as a workaround for now we can add the wheel group in the image creation phase for debian based images).

**Comment by debarshiray** [comment]
Closing as per #132
