### ISSUE TITLE
Created containers do not have network connection

### ISSUE THREAD

**Issue by ludwigd** [debarshiray/toolbox#152]
When creating a new toolbox container using  `./toolbox create -c test` and then entering it using `./toolbox enter --container test`, the container has no network connection (`ssh` and `dnf` fail).

However, I removed two lines from the toolbox script (see below) and the containers created afterwards do have network connection again. So maybe there is something wrong with how `$dns_none` and `$no_hosts` are set.

```
diff --git a/toolbox b/toolbox
index 4f3463f..884bdcc 100755
--- a/toolbox
+++ b/toolbox
@@ -938,13 +938,11 @@ create()
 
     # shellcheck disable=SC2086
     $prefix_sudo podman create \
-            $dns_none \
             $toolbox_path_set \
             --group-add wheel \
             --hostname toolbox \
             --name $toolbox_container \
             --network host \
-            $no_hosts \
             --pid host \
             --privileged \
             --security-opt label=disable \

```

System information:
```
rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/30/x86_64/silverblue
                   Version: 30.20190508.0 (2019-05-08T00:33:42Z)
                BaseCommit: 14a32e53de39e6c2d5893c7b63ebd8aa0ae5b3af83c95f88b8169b742e42d76d
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
           LayeredPackages: tilix util-linux-user zsh
```

I am using the latest toolbox (commit de67ff4bcc09a4d667943bbae1a98d34d3de9f1d).

**Comment by debarshiray** [comment]
`$dns_none` and `$no_hosts` comes from commit 04732139074b60dabe3087c37afbd99bdbf14a8a for PR #129 

I think what's happening is that you have a new toolbox script but an old image. This is the image that looks like `localhost/fedora-toolbox-$USER:30`, not the one that was pulled from the registry.

How do `/etc/hosts` and `/etc/resolv.conf` look inside your toolbox container? They should be symlinked to `/run/host/etc/hosts` and `/run/host/etc/resolv.conf` respectively, and `/etc` from your host should be bind mounted as `/run/host/etc` inside your container.

The workaround would be to `toolbox rmi` the image and try re-creating the container.

To reduce compatibility problems like these, I'd like to reshuffle the toolbox creation sequence to not involve the second intermediate OCI image, and instead configure the container in-place. Due to your issue, this task has now gotten bumped up my TODO list. :)

Thanks for stopping by!

**Comment by ludwigd** [comment]
Thanks for your reply.

I did `toolbox rmi` and recreated the container, but without luck. But I found that inside the container `/etc/resolve.conf` is not the one from the host, but `/run/host/etc/resolve.conf` is correct.

The attached log shows all my steps. I inserted some newlines for readability, but changed nothing else.

[toolbox-log.txt](https://github.com/debarshiray/toolbox/files/3163234/toolbox-log.txt)

**Comment by debarshiray** [comment]
I see. That's odd. It sounds like the `buildah unshare sh -c ...` commands are not being run. No idea why.

Could you please remove the image as before and re-create the container, but this time with the `--verbose` flag and paste the output? eg., `./toolbox --verbose create`.

What versions of `fuse-overlayfs` and `buildah` are you using? Use `rpm -q buildah fuse-overlayfs` if those are from the Fedora RPMs.

In the meanwhile, I will try to reproduce locally.

**Comment by ludwigd** [comment]
Here is the output you asked for...

```
$ rpm -q buildah fuse-overlayfs
buildah-1.7-18.git873f001.fc30.x86_64
fuse-overlayfs-0.3-8.dev.gita6958ce.fc30.x86_64
```
...and the log of `./toolbox --verbose create`

[toolbox-verbose.txt](https://github.com/debarshiray/toolbox/files/3166955/toolbox-verbose.txt)

**Comment by debarshiray** [comment]
> May I suggest the following patch? Adding dashes `--` to 'buildah unshare'
> seems to solve it. Following the man page for `buildah-unshare` it should be
> used this way: `buildah unshare [options] [--] [command]`. So the dashes are
> officially optional, but maybe they are needed because of all the quotes and
> that stuff.

You are 100% right! It turns out that the behaviour of Buildah changed after 1.7 (I have an unstable 1.8 pre-release snapshot).

Do you want to submit a pull request with that change? Or you can give me your `Full Name <email>` so that I can correctly attribute the commit to you.

Many thanks for sticking with this and figuring out the fix!

**Comment by ludwigd** [comment]
I sent a PR ( #156). However, since you are about to get rid of `buildah` I guess it won't get merged. Would be a logical decision.

**Comment by debarshiray** [comment]
> I sent a PR ( #156). However, since you are about to get rid of `buildah`
> I guess it won't get merged. Would be a logical decision.

Thanks for the PR! I am still happy to merge your change before the changes in #160. I think you deserve some credit for debugging this issue and finding out a fix. :)

May I have your email address so that I can properly attribute the commit in Git?
