### ISSUE TITLE
$SHELL variable set inconsistently

### ISSUE THREAD

**Issue by rugk** [debarshiray/toolbox#219]
For the whole backstory, see: https://discussion.fedoraproject.org/t/toolbox-and-zsh/2035?u=rugk

In short:
* zsh on the host
* in the pod, had no zsh installed, it seems bash was actually used
* toolbox enter

Related and possibly important: Podman crashed, see https://github.com/containers/libpod/issues/3520, but for whatever reason things™ still worked :wink: 

## What should have happened

If it actually uses bash, ` $SHELL`  should be ` bash` .

## What happened

It seems it used ` bash`  in reality, but ` $SHELL`  was set to ` zsh` .

## System

Fedora Silverblue 30
30.20190707.0 (2019-07-07T00:38:42Z)
BaseCommit: 751d21e610448544298604e5cd984179e62439cb253939cbb4d371d0661e1e74

**Comment by debarshiray** [comment]
> If it actually uses bash, $SHELL should be bash .

Umm... I don't think so. When my default shell is `/bin/bash` in `/etc/passwd`, if I manually spawn a zsh instance then the value of `SHELL` remains unchanged.
```
$ echo $SHELL
/bin/bash
$ zsh
% echo $SHELL
/bin/bash
```

This is what [POSIX](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html) has to say about `SHELL`:
*This variable shall represent a pathname of the user's preferred command language interpreter.*

Since the *preferred* command language interpreter hasn't changed, it makes sense that the variable stays the same.

Or did I misunderstand anything?

The current behaviour is:
If your preferred shell on the host isn't present in the toolbox container, then it will fallback to Bash. Once you install the relevant shell, it will get used.

**Comment by BrainBlasted** [comment]
Yup, it seems to work as intended if I set the shell on the host with lchsh and have it installed in toolbox

**Comment by rugk** [comment]
Yeah, okay, this was also my understanding, so it works as expected.
