### ISSUE TITLE
Braces or parentheses?

### ISSUE THREAD

**Issue by HarryPhoon** [debarshiray/toolbox#223]
We use both braces and parentheses in functions. Is that intentional? If not, wouldn't it be better, if we decided which to use? I can then convert the file.

**Comment by debarshiray** [comment]
It's a matter of whether we want to use a sub-shell or not. Braces don't create a new sub-shell, but parentheses do.

A sub-shell is generally better if the function has its own local variables. In that case those variables are going to be scoped to the sub-shell. Otherwise, we can skip the cost of creating a sub-shell.

There's also the case of `init_container()` where the final `exec sleep +Inf` doesn't work with a sub-shell.

Does this help? :)

**Comment by HarryPhoon** [comment]
Very. I didn't know there is a functional difference. Good to know.
