### ISSUE TITLE
'podman exec' resets the terminal size to 80x24

### ISSUE THREAD

**Issue by tagoh** [debarshiray/toolbox#242]
I'm not quite sure when toolbox changed this behavior, but it worked as expected. but now toolbox resets the terminal size to 80x24 even though it is not on host.

**Comment by mildred** [comment]
Could this be the cause of #14 ?

**Comment by tagoh** [comment]
No idea. this could be fixed by settings COLUMNS and LINES from host at least.

**Comment by pnemade** [comment]
I confirm I am too facing this issue and patch given in #243 fixes it.

**Comment by debarshiray** [comment]
> Could this be the cause of #14 ?

That's something else, I think. It was diagnosed in https://github.com/containers/libpod/issues/3179

**Comment by debarshiray** [comment]
> I'm not quite sure when toolbox changed this behavior, but it
> worked as expected. but now toolbox resets the terminal size to
> 80x24 even though it is not on host.

Indeed. I noticed it yesterday while playing with @HarryPhoon 's patches in https://github.com/debarshiray/toolbox/pull/200 Things like `less(1)` were not using the full window size.

It's something in Podman because it creates a nested pseudo-terminal pair inside the one created by the terminal emulation application. Possibly in runc because I think that's where the pseudo-terminal pair is created for `podman exec`.

**Comment by debarshiray** [comment]
Filed: https://github.com/containers/libpod/issues/3946

**Comment by debarshiray** [comment]
Interestingly, only the initial size is wrong. If the terminal emulator window is resized afterwards, then it picks up the changes correctly.
