### ISSUE TITLE
Simpler uidmap options for podman

### ISSUE THREAD

**Issue by dustymabe** [debarshiray/toolbox#244]
In cfcf4eb you did some nice investigatory work in tracking down how to call `--uidmap` properly to map the users id outside the container to the same id inside rootless podman container. I think we can achieve the same goal now with `podman --userns=keep-id`. At least it seems to be the case in my testing if I remove the `--uidmap` options and replace with `--userns=keep-id`: 

```
[vagrant@vanilla-f30 ~]$ toolbox enter
⬢[vagrant@toolbox ~]$ cat /proc/self/uid_map 
      1000          0          1
         0          1       1000
      1001       1001      64536
⬢[vagrant@toolbox ~]$ exit
logout
[vagrant@vanilla-f30 ~]$ sudi vi /usr/bin/toolbox 
-bash: sudi: command not found
[vagrant@vanilla-f30 ~]$ sudo vi /usr/bin/toolbox 
[vagrant@vanilla-f30 ~]$ 
[vagrant@vanilla-f30 ~]$ toolbox enter
⬢[vagrant@toolbox ~]$ 
⬢[vagrant@toolbox ~]$ cat /proc/self/uid_map 
      1000          0          1
         0          1       1000
      1001       1001      64536

```

Do you agree?

**Comment by debarshiray** [comment]
Yes, `--userns=keep-id` was added in https://github.com/containers/libpod/pull/3196 because more and more people have been using this pattern. :)

I am sometimes apprehensive of picking up niceties introduced in newer Podman versions because it can make it harder to bisect regressions in Podman with a newer Toolbox - the usual pain of tracking things across multiple Git repositories.

Anyway, I see that `--userns=keep-id` was introduced in Podman 1.4.0. Subsequent Podman releases have been relatively stable, and it's also old enough to be in RHELs 7 and 8. So it seems like a reasonable baseline to adopt.

Do you already have a patch tucked away somewhere? :)

**Comment by dustymabe** [comment]
> Do you already have a patch tucked away somewhere? :)

#252 :)
