### ISSUE TITLE
The toolbox should use the same time zone as the host

### ISSUE THREAD

**Issue by refi64** [debarshiray/toolbox#70]
I spent a good hour trying to debug my C program not displaying the time correctly before I realized it worked from the host system :sweat_smile: 

Currently, the time zone inside the toolbox is always set to UTC, regardless of the host time. (You can see this with a `file /etc/localtime`.) I'm guessing the fix would be to bind the host's /etc/localtime into the container?

**Comment by debarshiray** [comment]
This is similar to the `/etc/resolv.conf` problem that we have.

Bind mounting `/etc/localtime` will work as long as the system's timezone doesn't change. If it does, then the bind mount won't get updated because it will be considered a separate inode. This wouldn't have been a problem if we could bind mount an entire directory.

Flatpak solves this by adding another level of redirection into a separate directory which is kept updated by a helper process.

**Comment by juhp** [comment]
Mounting `/etc/localtime` seems good enough for now?

**Comment by debarshiray** [comment]
There's some Podman work going on in https://github.com/containers/libpod/issues/2744 that will let us solve this properly. I think this will be solved in the short-term.

**Comment by debarshiray** [comment]
There's a work-in-progress branch in #93
