### ISSUE TITLE
[RFE] Introduce a command to "delete" or "remove" a toolbox

### ISSUE THREAD

**Issue by felipeborges** [debarshiray/toolbox#85]
The joy of pet containers is in the ability to flush them out and start over.

Currently, I purge everything in ~/.local/share/containers/ whenever I need to start over.

Feel free to CLOSE if [RFE] don't belong in the Github Issues.

**Comment by debarshiray** [comment]
@ozoder already added `rm` and `rmi` in #45 and they are in `toolbox-0.0.7`. You might have to layer it in on Silverblue <= 29 because they are still stuck in `updates-testing`:
- https://bodhi.fedoraproject.org/updates/FEDORA-2019-8b8b177139
- https://bodhi.fedoraproject.org/updates/FEDORA-2019-52e62c5725

Or a workaround would be to use `podman rm` and `podman rmi`. The toolbox commands are just thin wrappers around them.

Thanks for stopping by. :)
